### ISSUE TITLE
Uncaught Error: Call to a member function payment_complete() 

### ISSUE THREAD

**Issue by BACCMED** [youssef-lmw/woocommerce-smt-clictopay#3]
I have this error when executing a payment with this extension
PHP Fatal error:  Uncaught Error: Call to a member function payment_complete() on bool in C:\\xampp\\htdocs\\wordpressShop\\wp-content\\plugins\\woocommerce-smt-clictopay-main\\woocommerce-smt-clictopay.php:214

**Comment by machour** [comment]
This means that 

```php
$order = wc_get_order($body['OrderNumber']);
```

returned false.

Can you check what's in the $body variable?
